In [26]:
# importing 
import pandas as pd
from sqlalchemy import create_engine

In [27]:
streaming_data = "final_stream.csv"
streaming_data_df = pd.read_csv(streaming_data)

In [28]:
streaming_data_df.head()

,index,id,title,year,age,imdb,rotten_tomatoes,netflix,hulu,prime_video,directors,genres,language,runtime
0,6674,6675,1 Night,2017,13+,5.8,33,False,False,True,Minhal Baig,Drama,English,80
1,16442,16443,101 Dalmatians II: Patch's London Adventure,2003,all,5.8,67,False,False,False,"Jim Kammerud,Brian Smith",Animation,English,74
2,5080,5081,11:55,2017,18+,4.9,100,False,False,True,"Ari Issler,Ben Snyder",Crime,English,80
3,1075,1076,13 Cameras,2015,18+,5.1,77,True,False,False,Victor Zarcoff,Crime,English,87
4,644,645,13 Sins,2014,18+,6.3,65,True,False,False,Daniel Stamm,Horror,English,93

In [29]:
connection_string = "admin1:12345@localhost:5432/Project#2"
engine = create_engine(f'postgresql://{connection_string}')

In [30]:
engine.table_names()

['netflix_stream']

In [31]:
# Below code worked and loaded successfully into pgAdmin Database table. 
streaming_data_df.to_sql(name='netflix_stream', con=engine, if_exists='append', index=False)

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "netflix_stream_pkey"
DETAIL:  Key (id)=(6675) already exists.

[SQL: INSERT INTO netflix_stream (index, id, title, year, age, imdb, rotten_tomatoes, netflix, hulu, prime_video, directors, genres, language, runtime) VALUES (%(index)s, %(id)s, %(title)s, %(year)s, %(age)s, %(imdb)s, %(rotten_tomatoes)s, %(netflix)s, %(hulu)s, %(prime_video)s, %(directors)s, %(genres)s, %(language)s, %(runtime)s)]
[parameters: ({'index': 6674, 'id': 6675, 'title': '1 Night', 'year': 2017, 'age': '13+', 'imdb': 5.8, 'rotten_tomatoes': 33, 'netflix': False, 'hulu': False, 'prime_video': True, 'directors': 'Minhal Baig', 'genres': 'Drama', 'language': 'English', 'runtime': 80}, {'index': 16442, 'id': 16443, 'title': "101 Dalmatians II: Patch's London Adventure", 'year': 2003, 'age': 'all', 'imdb': 5.8, 'rotten_tomatoes': 67, 'netflix': False, 'hulu': False, 'prime_video': False, 'directors': 'Jim Kammerud,Brian Smith', 'genres': 'Animation', 'language': 'English', 'runtime': 74}, {'index': 5080, 'id': 5081, 'title': '11:55', 'year': 2017, 'age': '18+', 'imdb': 4.9, 'rotten_tomatoes': 100, 'netflix': False, 'hulu': False, 'prime_video': True, 'directors': 'Ari Issler,Ben Snyder', 'genres': 'Crime', 'language': 'English', 'runtime': 80}, {'index': 1075, 'id': 1076, 'title': '13 Cameras', 'year': 2015, 'age': '18+', 'imdb': 5.1, 'rotten_tomatoes': 77, 'netflix': True, 'hulu': False, 'prime_video': False, 'directors': 'Victor Zarcoff', 'genres': 'Crime', 'language': 'English', 'runtime': 87}, {'index': 644, 'id': 645, 'title': '13 Sins', 'year': 2014, 'age': '18+', 'imdb': 6.3, 'rotten_tomatoes': 65, 'netflix': True, 'hulu': False, 'prime_video': False, 'directors': 'Daniel Stamm', 'genres': 'Horror', 'language': 'English', 'runtime': 93}, {'index': 87, 'id': 88, 'title': '13th', 'year': 2016, 'age': '18+', 'imdb': 8.2, 'rotten_tomatoes': 96, 'netflix': True, 'hulu': False, 'prime_video': False, 'directors': 'Ava DuVernay', 'genres': 'Documentary', 'language': 'English', 'runtime': 100}, {'index': 13164, 'id': 13165, 'title': '13th Child', 'year': 2002, 'age': '18+', 'imdb': 2.9, 'rotten_tomatoes': 40, 'netflix': False, 'hulu': False, 'prime_video': True, 'directors': 'Thomas Ashley,Steven Stockage', 'genres': 'Horror', 'language': 'English', 'runtime': 99}, {'index': 2222, 'id': 2223, 'title': '14 Cameras', 'year': 2018, 'age': '18+', 'imdb': 4.5, 'rotten_tomatoes': 22, 'netflix': True, 'hulu': False, 'prime_video': False, 'directors': 'Seth Fuller,Scott Hussion', 'genres': 'Crime', 'language': 'English', 'runtime': 90}  ... displaying 10 of 1796 total bound parameter sets ...  {'index': 16225, 'id': 16226, 'title': 'Zootopia', 'year': 2016, 'age': '7+', 'imdb': 8.0, 'rotten_tomatoes': 98, 'netflix': False, 'hulu': False, 'prime_video': False, 'directors': 'Byron Howard,Rich Moore,Jared Bush', 'genres': 'Animation', 'language': 'English', 'runtime': 108}, {'index': 4529, 'id': 4530, 'title': 'mid90s', 'year': 2018, 'age': '18+', 'imdb': 7.4, 'rotten_tomatoes': 81, 'netflix': False, 'hulu': False, 'prime_video': True, 'directors': 'Jonah Hill', 'genres': 'Comedy', 'language': 'English', 'runtime': 85})]
(Background on this error at: http://sqlalche.me/e/gkpj)

In [32]:
# make sure connection worked
pd.read_sql_query('select * from netflix_stream', con=engine).head()

,index,id,title,year,age,imdb,rotten_tomatoes,netflix,hulu,prime_video,directors,genres,language,runtime
0,6674,6675,1 Night,2017,13+,5.8,33,False,False,True,Minhal Baig,Drama,English,80.0
1,16442,16443,101 Dalmatians II: Patch's London Adventure,2003,all,5.8,67,False,False,False,"Jim Kammerud,Brian Smith",Animation,English,74.0
2,5080,5081,11:55,2017,18+,4.9,100,False,False,True,"Ari Issler,Ben Snyder",Crime,English,80.0
3,1075,1076,13 Cameras,2015,18+,5.1,77,True,False,False,Victor Zarcoff,Crime,English,87.0
4,644,645,13 Sins,2014,18+,6.3,65,True,False,False,Daniel Stamm,Horror,English,93.0